# Generated by Django 4.0.3 on 2022-04-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='任务名称')),
                ('content', models.TextField(verbose_name='任务内容')),
                ('creat_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('lev', models.SmallIntegerField(choices=[(0, '正常'), (1, '紧急'), (2, '迫切')], default=0, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(0, '未完成'), (1, '完成'), (2, '丢弃')], default=0, verbose_name='完成情况')),
                ('per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.userinfo', verbose_name='负责人')),
            ],
        ),
    ]
